server:
  port: 8089

aplication:
  version: #application.version#
info:
  build:
    version: #application.version#
  app:
    description: API para gerenciar campanhas de clubes



spring:
    main:
      banner-mode: "off"
    datasource:
      url: jdbc:postgresql://localhost:5432/campaigndb
      driverClassName: org.postgresql.Driver
      username: postgres
      password: hpaiva
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      open-in-view: false
      show-sql: true
      properties:
        hibernate:
          jdbc:
            lob:
              non_contextual_creation: true
rabbitmq:
    queueName: campaign.queue
    exchangeName: campaign-exchange
    routingKey: campaign.routingkey