server:
  port: 8089

aplication:
  version: #application.version#
info:
  build:
    version: #application.version#
  app:
    description: API para gerenciar campanhas de clubes



spring:
    main:
      banner-mode: "off"
    datasource:
      url: jdbc:h2:mem:campaigndb;
      driverClassName: org.h2.Driver
      username: hpaiva
      password: hpaiva
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    h2:
      console:
        enabled: true

rabbitmq:
    queueName: campaign.queue
    exchangeName: campaign-exchange
    routingKey: campaign.routingkey